name: build-docs

on:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  build-docs:
    # For internal PRs, this will run on `push` events;
    #   for external/forked PRs, it will run on `pull_request` events.
    #   Ideally we'd have checked this condition when defining the triggers,
    #   but that's not supported by GitHub actions.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
