name: build-docs

on: pull_request

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Cache Docusaurus
        uses: ./.github/actions/docusaurus-cache
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
