name: check-format
on: [pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Verify format with Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: added
          reporter: github-pr-review
