name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  linkChecker:
    name: Check links for url ${{ matrix.url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ["https://docs.camunda.io", "https://stage.docs.camunda.io"]
    steps:
      - uses: actions/checkout@v2
      - name: Download sitemap from production
        run: curl -sL https://docs.camunda.io/sitemap.xml | grep -oP '<loc>\K.*?(?=</loc>)' | sed "s!https://docs.camunda.io!${{ matrix.url }}!g" > sitemap.prod.txt
      - name: Prepare product links
        run: grep 'https://docs.camunda.io' product-links.txt | sed "s!https://docs.camunda.io!${{ matrix.url }}!g" > product-links.prod.txt
      - name: Check internal links
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: "--connection-failures-as-warnings -i sitemap.prod.txt"
      - name: Check product links
        uses: filiph/linkcheck@2.0.23
        with:
          arguments: "--connection-failures-as-warnings -i product-links.prod.txt"
