name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "* 22 * * *"

jobs:
  linkChecker:
    name: Check links for url ${{ matrix.url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: [ "https://docs.camunda.io", "https://stage.docs.camunda.io" ]
    steps:
      - uses: filiph/linkcheck@v2.0.15+1
        with:
          arguments: ${{ matrix.url }}
