---
# desc: lint sanity check
name: Links (Fail Fast)

on:
  push:
  workflow_dispatch:


jobs:
    lint:
        name: links-check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
            - name: Restore lychee cache
              uses: actions/cache@v3
              with:
                path: .lycheecache
                key: cache-lychee-${{ github.sha }}
                restore-keys: cache-lychee-
                    
            - name: Link Checker
              uses: lycheeverse/lychee-action@v1.9.0
              with:
                fail: true
                args: -c ./lychee.toml --base . --cache --max-cache-age 1d . --verbose --no-progress 'docs/**/*.md' 'versioned_docs/**/*.md'

            # - name: Create Issue From File
            #   if: env.lychee_exit_code != 0
            #   uses: peter-evans/create-issue-from-file@v4
            #   with:
            #     title: Link Checker Report
            #     content-filepath: ./lychee/out.md
            #     labels: report, automated issue