name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  linkChecker:
    name: Check links for url ${{ matrix.url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: [ "https://docs.camunda.io", "https://stage.docs.camunda.io" ]
    steps:
      - name: Download sitemap from production
        run: curl -sL https://docs.camunda.io/sitemap.xml | grep -oP '<loc>\K.*?(?=</loc>)' | sed "s!https://docs.camunda.io!${{ matrix.url }}!g" > sitemap.txt
        # disable action until https://github.com/tylerbutler/linkcheck-bin/issues/1 is released
        #uses: filiph/linkcheck@v2.0.20
        #with:
        #  arguments: '-i sitemap.prod.txt'
      - name: Check internal links from sitemap
        run: |
          curl -sL https://github.com/filiph/linkcheck/releases/download/2.0.20/linkcheck-2.0.20-linux-x64.tar.gz | tar xvzf - linkcheck/linkcheck --strip 1
          ./linkcheck -i sitemap.txt
