name: move-to-done

# FYI secrets.ADD_TO_PROJECT_PAT is a personal access token belonging to @akeller.

on:
  pull_request:
    # sjh: `labeled`/`unlabeled` for now! but when this is ready to go, change to `closed`.
    types: [labeled, unlabeled]

jobs:
  move-to-done:
    # sjh: uncomment this if when we change the trigger to `closed`
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get project IDs for later steps
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          ORGANIZATION: camunda
          PROJECT_NUMBER: 27
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!, $prID: ID!) {
              node(id: $prID) {
                ... on PullRequest {
                  projectItems(first: 10) {
                    nodes {
                      id
                      project {
                        number
                      }
                    }
                  }
                }
              }
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER -f prID=${{github.event.pull_request.node_id}} > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'DONE_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="✅ Done") |.id' project_data.json) >> $GITHUB_ENV
          echo 'PROJECT_ITEM_ID='$(jq '.data.node.projectItems.nodes[] | select(.project.number== ${{ env.PROJECT_NUMBER }}) | .id' project_data.json) >> $GITHUB_ENV
      - name: Output found values
        run: |
          echo 'PROJECT_ID=${{ env.PROJECT_ID }}'
          echo 'STATUS_FIELD_ID=${{ env.STATUS_FIELD_ID }}'
          echo 'DONE_OPTION_ID=${{ env.DONE_OPTION_ID }}'
          echo 'PR_ID=${{ github.event.pull_request.node_id }}'
          echo 'PROJECT_ITEM_ID=${{ env.PROJECT_ITEM_ID }}'

      # - name: Add PR to project
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
      #     PR_ID: ${{ github.event.pull_request.node_id }}
      #   run: |
      #     item_id="$( gh api graphql -f query='
      #       mutation($project:ID!, $pr:ID!) {
      #         addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
      #           item {
      #             id
      #           }
      #         }
      #       }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectV2ItemById.item.id')"

      #       echo 'ITEM_ID='$item_id >> $GITHUB_ENV
      # - name: Set status field
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
      #   run: |
      #     gh api graphql -f query='
      #       mutation (
      #         $project: ID!
      #         $item: ID!
      #         $status_field: ID!
      #         $status_value: String!
      #       ) {
      #         set_status: updateProjectV2ItemFieldValue(input: {
      #           projectId: $project
      #           itemId: $item
      #           fieldId: $status_field
      #           value: {
      #             singleSelectOptionId: $status_value
      #             }
      #         }) {
      #           projectV2Item {
      #             id
      #             }
      #         }
      #       }' -f project=$PROJECT_ID -f item=$ITEM_ID -f status_field=$STATUS_FIELD_ID -f status_value=${{ env.IN_REVIEW_OPTION_ID }}
